import React from 'react';
import { Sparkles, Bot, AlertCircle, CheckSquare } from 'lucide-react';

const AIExplanation = () => {
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '2rem' }}>
      <div>
        <h2 style={{ fontSize: '1.75rem', fontWeight: 800, color: '#fff', marginBottom: '0.4rem' }}>
          AI Narrative Explanations
        </h2>
        <p style={{ color: 'var(--text-muted)' }}>
          LLM-generated root cause diagnostic summaries and automated fix recommendations.
        </p>
      </div>

      <div className="glass-card" style={{ padding: '2rem', border: '1px solid rgba(139, 92, 246, 0.3)' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', marginBottom: '1.5rem' }}>
          <div style={{ background: 'var(--gradient-primary)', padding: '0.5rem', borderRadius: '10px' }}>
            <Bot size={24} color="#fff" />
          </div>
          <div>
            <h3 style={{ fontSize: '1.2rem', fontWeight: 700, color: '#fff' }}>Dataset Health Narrative</h3>
            <span style={{ color: 'var(--text-dim)', fontSize: '0.85rem' }}>Generated by GPT-4 / Anthropic Claude LLM Engine</span>
          </div>
        </div>

        <div style={{
          background: 'rgba(0,0,0,0.3)',
          padding: '1.5rem',
          borderRadius: '12px',
          color: 'var(--text-main)',
          fontSize: '0.95rem',
          lineHeight: 1.7,
          marginBottom: '1.5rem',
          borderLeft: '4px solid var(--accent-primary)'
        }}>
          <p style={{ marginBottom: '1rem' }}>
            <strong>Executive Summary:</strong> The processed dataset <code>ecommerce_transactions.csv</code> scored an overall <strong>94.2/100</strong>. The data exhibits high structural completeness (98.2%), but contains 14 statistical anomalies primarily concentrated in the <code>Price</code> and <code>Quantity</code> features.
          </p>
          <p>
            <strong>Root Cause Analysis:</strong> Three transactions reported extreme price spikes (&gt; 3.5 Z-score standard deviations), traced back to missing currency decimal points during client-side payment gateway serialization.
          </p>
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: '1rem' }}>
          <div style={{ background: 'rgba(244, 63, 94, 0.1)', padding: '1rem 1.25rem', borderRadius: '12px', border: '1px solid rgba(244, 63, 94, 0.2)' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', color: 'var(--accent-rose)', fontWeight: 700, marginBottom: '0.4rem' }}>
              <AlertCircle size={18} /> High Priority Alert
            </div>
            <p style={{ color: 'var(--text-muted)', fontSize: '0.85rem' }}>
              Row #142 has an unparsed price string formatted as <code>"8450000"</code> instead of <code>"$845.00"</code>.
            </p>
          </div>

          <div style={{ background: 'rgba(16, 185, 129, 0.1)', padding: '1rem 1.25rem', borderRadius: '12px', border: '1px solid rgba(16, 185, 129, 0.2)' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', color: 'var(--accent-emerald)', fontWeight: 700, marginBottom: '0.4rem' }}>
              <CheckSquare size={18} /> Recommended Action
            </div>
            <p style={{ color: 'var(--text-muted)', fontSize: '0.85rem' }}>
              Run the automated <code>cleaning.ipynb</code> script to parse prices and impute missing date stamps.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default AIExplanation;
