import React, { useEffect, useState } from 'react';

import MetricCard from '../components/MetricCard';
import ChartCard from '../components/ChartCard';
import DataTable from '../components/DataTable';
import PlotlyChart from '../components/PlotlyChart';

import { useDataset } from '../context/DatasetContext';

import {
  Award,
  AlertTriangle,
  FileSpreadsheet,
  ShieldAlert
} from 'lucide-react';


// ---------------------------------------------------------
// Dataset table columns
// ---------------------------------------------------------

const columns = [
  {
    header: 'ID',
    key: '_id'
  },

  {
    header: 'Dataset Name',
    key: 'originalName'
  },

  {
    header: 'Size (KB)',
    render: (row) =>
      `${((row.size || 0) / 1024).toFixed(1)} KB`
  },

  {
    header: 'Status',
    render: (row) => (
      <span
        style={{
          textTransform: 'capitalize',
          color: 'var(--accent-emerald)'
        }}
      >
        {row.status}
      </span>
    )
  },

  {
    header: 'Uploaded Date',
    render: (row) =>
      new Date(
        row.uploadedAt || Date.now()
      ).toLocaleDateString()
  }
];


// ---------------------------------------------------------
// Dashboard
// ---------------------------------------------------------

const Dashboard = () => {

  const {
    dashboardStats,
    datasetsList,
    activeDataset
  } = useDataset();


  // -------------------------------------------------------
  // Plotly chart state
  // -------------------------------------------------------

  const [charts, setCharts] = useState(null);

  const [chartsLoading, setChartsLoading] = useState(true);

  const [chartsError, setChartsError] = useState(null);


  // -------------------------------------------------------
  // Load Plotly charts generated by ML Engine
  // -------------------------------------------------------

  useEffect(() => {

    const loadCharts = async () => {

      try {

        setChartsLoading(true);

        setChartsError(null);

        const response = await fetch(
          'http://localhost:5000/reports/dashboard/dashboard_charts.json'
        );

        if (!response.ok) {

          throw new Error(
            `Failed to load dashboard charts: ${response.status}`
          );

        }

        const data = await response.json();

        console.log(
          'Interactive dashboard charts loaded:',
          data
        );

        setCharts(data);

      } catch (error) {

        console.error(
          'Dashboard chart error:',
          error
        );

        setChartsError(
          error.message
        );

      } finally {

        setChartsLoading(false);

      }

    };


    loadCharts();

  }, []);


  // -------------------------------------------------------
  // Existing dashboard statistics
  // -------------------------------------------------------

  const stats = dashboardStats || {

    overallQualityScore: 94.2,

    totalDatasetsProcessed:
      datasetsList?.length || 1,

    totalAnomaliesDetected: 14,

    criticalAlerts: 2

  };


  // -------------------------------------------------------
  // Dataset table
  // -------------------------------------------------------

  const runsTable =
    datasetsList &&
    datasetsList.length > 0

      ? datasetsList

      : [

          {
            _id: 'DS-901',

            originalName:
              'ecommerce_transactions.csv',

            size: 245000,

            status: 'uploaded',

            uploadedAt:
              new Date().toISOString()
          }

        ];


  // -------------------------------------------------------
  // Render
  // -------------------------------------------------------

  return (

    <div
      style={{
        display: 'flex',
        flexDirection: 'column',
        gap: '2rem'
      }}
    >

      {/* =================================================
          HEADER
      ================================================= */}

      <div>

        <h2
          style={{
            fontSize: '1.75rem',
            fontWeight: 800,
            color: '#fff',
            marginBottom: '0.4rem'
          }}
        >
          Executive System Dashboard
        </h2>

        <p
          style={{
            color: 'var(--text-muted)',
            margin: 0
          }}
        >
          Real-time metrics and quality scoring trends for{' '}

          <span
            style={{
              color: '#fff',
              fontWeight: 600
            }}
          >
            {activeDataset?.originalName ||
              'Active Dataset'}
          </span>
        </p>

      </div>


      {/* =================================================
          KPI CARDS
      ================================================= */}

      <div
        style={{
          display: 'flex',
          gap: '1.5rem',
          flexWrap: 'wrap'
        }}
      >

        <MetricCard
          title="Overall Quality Score"
          value={`${stats.overallQualityScore} / 100`}
          subtitle="Current dataset quality"
          trend="up"
          trendValue="+3.2%"
          icon={Award}
          color="var(--accent-primary)"
        />


        <MetricCard
          title="Total Datasets Processed"
          value={
            stats.totalDatasetsProcessed ||
            datasetsList?.length ||
            1
          }
          subtitle="Registered in system"
          icon={FileSpreadsheet}
          color="var(--accent-cyan)"
        />


        <MetricCard
          title="Anomalies Detected"
          value={
            stats.totalAnomaliesDetected ?? 0
          }
          subtitle="Detected by ML engine"
          trend="down"
          trendValue="-14%"
          icon={AlertTriangle}
          color="var(--accent-amber)"
        />


        <MetricCard
          title="Critical Rule Violations"
          value={
            stats.criticalAlerts ?? 0
          }
          subtitle="Requires attention"
          icon={ShieldAlert}
          color="var(--accent-rose)"
        />

      </div>


      {/* =================================================
          INTERACTIVE PLOTLY CHARTS
      ================================================= */}

      <div>

        <div
          style={{
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'center',
            marginBottom: '1rem'
          }}
        >

          <div>

            <h3
              style={{
                fontSize: '1.3rem',
                fontWeight: 700,
                color: '#fff',
                margin: 0
              }}
            >
              Interactive Analytics
            </h3>

            <p
              style={{
                color: 'var(--text-muted)',
                marginTop: '0.35rem',
                fontSize: '0.85rem'
              }}
            >
              Explore quality, anomaly and rule-violation
              results interactively.
            </p>

          </div>

        </div>


        {/* Chart loading */}

        {chartsLoading && (

          <div
            className="glass-card"
            style={{
              padding: '2rem',
              textAlign: 'center',
              color: 'var(--text-muted)'
            }}
          >
            Loading interactive charts...
          </div>

        )}


        {/* Chart error */}

        {!chartsLoading &&
          chartsError && (

            <div
              className="glass-card"
              style={{
                padding: '1.5rem',
                border:
                  '1px solid rgba(244, 63, 94, 0.3)',
                color:
                  'var(--accent-rose)'
              }}
            >

              Unable to load interactive
              dashboard charts.

              <div
                style={{
                  marginTop: '0.5rem',
                  fontSize: '0.8rem',
                  color: 'var(--text-muted)'
                }}
              >
                {chartsError}
              </div>

            </div>

          )}


        {/* Charts */}

        {!chartsLoading &&
          !chartsError &&
          charts && (

            <div
              style={{
                display: 'grid',
                gridTemplateColumns:
                  'repeat(auto-fit, minmax(420px, 1fr))',
                gap: '1.5rem'
              }}
            >

              {/* =========================================
                  QUALITY METRICS
              ========================================= */}

              <ChartCard
                title="Data Quality Metrics"
                subtitle="Completeness, uniqueness, validity and rules quality"
              >

                <PlotlyChart
                  figure={
                    charts.quality_metrics
                  }
                  height={350}
                />

              </ChartCard>


              {/* =========================================
                  QUALITY SCORE
              ========================================= */}

              <ChartCard
                title="Overall Quality Score"
                subtitle="Current dataset quality distribution"
              >

                <PlotlyChart
                  figure={
                    charts.quality_score
                  }
                  height={350}
                />

              </ChartCard>


              {/* =========================================
                  ANOMALY DISTRIBUTION
              ========================================= */}

              <ChartCard
                title="Anomaly Distribution"
                subtitle="Normal records versus detected anomalies"
              >

                <PlotlyChart
                  figure={
                    charts.anomaly_distribution
                  }
                  height={350}
                />

              </ChartCard>


              {/* =========================================
                  BUSINESS RULE VIOLATIONS
              ========================================= */}

              <ChartCard
                title="Business Rule Violations"
                subtitle="Detected data-quality rule violations"
              >

                <PlotlyChart
                  figure={
                    charts.business_rules
                  }
                  height={400}
                />

              </ChartCard>

            </div>

          )}

      </div>


      {/* =================================================
          REGISTERED DATASETS
      ================================================= */}

      <div
        className="glass-card"
        style={{
          padding: '1.5rem'
        }}
      >

        <h3
          style={{
            fontSize: '1.1rem',
            fontWeight: 700,
            color: '#fff',
            marginBottom: '1rem'
          }}
        >
          Registered Datasets
        </h3>

        <DataTable
          columns={columns}
          data={runsTable}
        />

      </div>

    </div>

  );

};


export default Dashboard;